### ISSUE TITLE
How do I get access to control the animation properties

### ISSUE THREAD

**Issue by samducker** [giuseppelt/astro-lottie#1]
Hey so I'm using this plugin as having issues using lottie-web in an astro component.

Your library does not allow me access the methods such as play and pause is that correct? (I am using this for a mobile menu animation) 

If so how could I go about doing this.

**Comment by giuseppelt** [comment]
Actually not possible. Give me a day, I'm working on a new version with that feature.

**Comment by giuseppelt** [comment]
Closed by ef05f31799cbf5fec94a962037151f2d4f146874.
I pushed the v0.2.0. Now you can access the Lottie player for any animation. Checkout the updated ReadMe and let me know if you have any issue.

**Comment by samducker** [comment]
@giuseppelt amazing work! This is going to make the site look great I really appreciate it.
