### ISSUE TITLE
Warning about security risk on build

### ISSUE THREAD

**Issue by fabianwurk** [giuseppelt/astro-lottie#11]
When running a build I am getting this warning:

`building client (vite) 
node_modules/lottie-web/build/player/lottie.js (17010:32): Use of eval in "node_modules/lottie-web/build/player/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.`

Is anyone else experiencing this same issue, and is there a way to resolve it?

**Comment by giuseppelt** [comment]
You can ignore that warning, it's within the lottie library and it's how it works.
A future update, may resolve that issue.

**Comment by jcenlo** [comment]
@giuseppelt i found this , i know is not the best solution but at least works

> Replacing import lottie from "lottie-web"; with import lottie from "lottie-web/build/player/lottie_light"; and using renderer: "svg", worked for me.

[https://github.com/airbnb/lottie-web/issues/289#issuecomment-1454909624](https://github.com/airbnb/lottie-web/issues/289#issuecomment-1454909624)

**Comment by giuseppelt** [comment]
@jcenlo this plug-in already does that, just set the `player="light"` in the component

**Comment by jcenlo** [comment]
Thanks
