### ISSUE TITLE
Use files hosted on another domain

### ISSUE THREAD

**Issue by regisphilibert** [giuseppelt/astro-lottie#12]
Hello and thanks for this integration! It comes very handy!

When I try to use a remote url as the `src` prop, understand a file not hosted on the same domain, I get:

``` 
<LottieAnimation src="https://www.example.com/animations/home.hero.json" autoplay="visible" />
```

```
page.js:125 Cannot load animation(https://www.example.com/animations/home.hero.json)
(anonymous) @ page.js:125Understand this warning
page.js:39 Skipped animation(https://www.example.com/animations/home.hero.json) due to missing data
```

I'm not seeing any CORS error so I have to assume this is not the cause of this. Am I missing anything?

**Comment by giuseppelt** [comment]
The browser cannot load that file.
You should see something in the network tab of chrome.

**Comment by regisphilibert** [comment]
So sorry I was not able to identify the CORS issue on the remote server (not my site...) before bugging you! Thank for your time and for this integration!
