### ISSUE TITLE
Allow control over IntersectionObserver threshold

### ISSUE THREAD

**Issue by arkwismb** [giuseppelt/astro-lottie#3]
Any plans to let us control the threshold? Would be great to have that as an option

**Comment by giuseppelt** [comment]
What's your scenario? Which value are you looking for?
________________________________
From: arkwismb ***@***.***>
Sent: Thursday, April 6, 2023 10:30:25 PM
To: giuseppelt/astro-lottie ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [giuseppelt/astro-lottie] Allow control over IntersectionObserver threshold (Issue #3)


Any plans to let us control the threshold? Would be great to have that as an option

**Comment by arkwismb** [comment]
Might've understood it wrong and `rootMargin` could be a better choice but basically want to start the animation only when 25% of element is in view, and then pause it again when less than 25% of the element is left in view.

**Comment by giuseppelt** [comment]
The new `visibleThreshold` config in the v0.2.2 should cover this
