### ISSUE TITLE
Support for astro view transitions

### ISSUE THREAD

**Issue by Jenrykster** [giuseppelt/astro-lottie#7]
I've been struggling with using this package and astro view transitions, after changing routes for the first time the animations disappear. 
At first, I just started calling `loadLottie` on the `astro:after-swap` event. But after I added a lottie animation on the header (which is present on all routes) the header animation starts getting duplicated when `loadLottie` is called.

Right now I got it working with a workaround by clearing the children of the containers before loading the animations on `loadLottie`.

Is there a better solution for this? 

Also, thanks for the work on the package.

**Comment by tsevdos** [comment]
Hello @Jenrykster ,

Can you please share your work-around?

**Comment by Jenrykster** [comment]
@tsevdos 

Yeah sure, sorry for taking so long to reply.

You can look at this [repo](https://github.com/Jenrykster/astro-blog) to see an actual implementation. 
But basically what I did was: expose a `loadLottie` method on the source of the package (I used patch-package to keep those changes on the repo, so you can look at the exact diffs on the patches folder). Then I add the following script to the page where I have an animation.

```js
  document.addEventListener("astro:after-swap", () => {
    // I'm passing the name of the animation to avoid duplicating persistent ones (like in the header) 
    window.loadLottie("wave-animation");
  });
  window.loadLottie("wave-animation");
```

**Comment by kershnerd** [comment]
I am also having the same issue.  Is there a fix for this or do we have to use this work around?

**Comment by giuseppelt** [comment]
Working on it, I'll push support for transitions soon.
Sorry for the long time.

**Comment by kershnerd** [comment]
Thank you @giuseppelt .  I don't know enough about transitions to help otherwise I would have attempted a PR myself.  I appreciate your help!
